Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest:25565, host:25565, auto_correct: false
  config.vm.synced_folder "MCServer/", "/home/vagrant/MCServer"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end
  config.vm.provision "shell", path: "scripts/init.sh"
  config.vm.provision "shell", path: "scripts/mcserver_setup.sh", privileged: false
end
  