Vagrant.configure("2") do |config|
    config.vm.define :reverseproxy do |reverseproxy|
        reverseproxy.vm.box = "ubuntu/xenial64"
        reverseproxy.vm.network :private_network, ip: "10.0.0.10"
        reverseproxy.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
        reverseproxy.vm.synced_folder "configs/", "/etc/apache2/sites-enabled/"
        reverseproxy.vm.hostname = "reverseproxy"

        reverseproxy.vm.provision "shell", inline: <<-SHELL
            apt-get update
            sudo apt-get install apache2 -y
            sudo apt-get install ufw -y
            sudo apt-get install libapache2-mod-proxy-html -y
            sudo apt-get install libxml2-dev -y

            sudo a2enmod proxy
            sudo a2enmod proxy_html
            sudo a2enmod proxy_http

            sudo ufw allow from 10.0.2.2 to any port 22
            sudo ufw allow 80/tcp
            sudo ufw --force enable
        SHELL
        reverseproxy.vm.provision "shell", path: "scripts/init.sh"
        reverseproxy.vm.provision "shell", inline: <<-SHELL
            sudo service apache2 restart
        SHELL
    end



    config.vm.define :web do |web|
        web.vm.box = "ubuntu/xenial64"
        web.vm.network :private_network, ip: "10.0.0.20"
        web.vm.hostname = "web"
        web.vm.synced_folder "html/", "/var/www/html"
        web.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get -y install apache2 ufw -y
        sudo ufw allow from 10.0.2.2 to any port 22
        sudo ufw allow from 10.0.0.10 to any port 80
        sudo ufw --force enable
        SHELL
    end
end