Vagrant.configure("2") do |config|
    box = "ubuntu/xenial64"
  
    config.vm.define "ldap" do |ldap|
      ldap.vm.box = box
      ldap.vm.network :private_network, ip: "10.0.0.10"
      ldap.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
      end
      ldap.vm.provision "shell", path: "scripts/ldap-setup.sh"
    end
  
    config.vm.define "web" do |web|
      web.vm.box = box
      web.vm.network :private_network, ip: "10.0.0.20"
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
      end
      web.vm.provision "shell", path: "scripts/web-setup.sh"
    end
  
  end
  